{{- range $version := (list "v1" "v2") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{ $version }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: my-app
    version: {{ $version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: {{ $version }}
  template:
    metadata:
      labels:
        app: my-app
        version: {{ $version }}
    spec:
      containers:
      - name: app
        image: nginx
{{- end }}